apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Cluster
  region: us-east-2

vpc:
  id: vpc-07ddf897fb87f9816
  cidr: "192.168.0.0/16"
  subnets:
    public:
      us-east-2a:
        id: subnet-03fac95f0a20ce59c
      us-east-2b:
        id: subnet-053a923b639b189f0
    private:
      us-east-2a:
        id: subnet-0586f25604eb6d409
      us-east-2b:
        id: subnet-0517ee354d1d11bd4

nodeGroups:
  - name: EKS-public-worker-node-group
    instanceType: t3.medium
    desiredCapacity: 2
  - name: EKS-private-worker-node-group
    instanceType: t3.medium
    desiredCapacity: 1
    privateNetworking: true
