AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for provisioning networking resources and an EKS cluster

Parameters:
  VpcCIDR:
    Type: String
    Default: "10.0.0.0/16"
    Description: CIDR block for the VPC

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyEKS-VPC

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: "10.0.1.0/24"
      AvailabilityZone: !Select [ 0, !GetAZs ap-south-1 ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet1

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: "10.0.2.0/24"
      AvailabilityZone: !Select [ 1, !GetAZs ap-south-1 ]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: PrivateSubnet1

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EKS nodes
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000  # Expose port 3000
          ToPort: 3000    # Expose port 3000
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: EKS-SecurityGroup

  EKSIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: EKSNodePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ec2:DescribeInstances"
                  - "ec2:DescribeTags"
                  - "ec2:DescribeRouteTables"
                  - "ec2:DescribeSecurityGroups"
                  - "ec2:DescribeSubnets"
                  - "ec2:DescribeVolumes"
                  - "ec2:DescribeVpcs"
                Resource: "*"

  MyEKSCluster:
      Type: AWS::EKS::Cluster
      Properties:
        Name: chesscluster
        RoleArn: !GetAtt EKSIAMRole.Arn
        ResourcesVpcConfig:
          SubnetIds:
            - !Ref PublicSubnet1
            - !Ref PrivateSubnet1
          SecurityGroupIds:
            - !GetAtt SecurityGroup.GroupId

  EKSNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref MyEKSCluster
      NodegroupName: MyNodeGroup
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PrivateSubnet1
      InstanceTypes:
        - t3.medium  # Instance type for worker nodes
      ScalingConfig:
        MinSize: 2  # Minimum number of nodes
        DesiredSize: 2  # Desired number of nodes
        MaxSize: 5  # Maximum number of nodes
      NodeRole: !GetAtt EKSIAMRole.Arn  # IAM role for the nodes

Outputs:
  VPCId:
    Description: VPC ID
    Value: !Ref VPC
  PublicSubnetId1:
    Description: Public Subnet ID 1
    Value: !Ref PublicSubnet1
  PrivateSubnetId1:
    Description: Private Subnet ID 1
    Value: !Ref PrivateSubnet1
  SecurityGroupId:
    Description: Security Group ID
    Value: !GetAtt SecurityGroup.GroupId
  EKSIAMRoleId:
    Description: EKS IAM Role ID
    Value: !Ref EKSIAMRole
