apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: chess-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chess-web-deployment  # Updated deployment name for consistency
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
