apiVersion: v1
kind: Service
metadata:
  name: chess-app-service
  labels:
    app: chess-web-app
spec:
  type: NodePort
  selector:
    app: chess-web-app
  ports:
    - nodePort: 31479
      port: 8080
      targetPort: 3000
