name: Delete-EKS-Cluster

on:
  workflow_dispatch:

jobs:
  Delete-EKS-Cluster:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Delete EKS Cluster
      run: |
        aws cloudformation delete-stack --stack-name my-eks-cluster

  Delete-Networking:
    runs-on: ubuntu-latest
    needs: [Delete-EKS-Cluster]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Delete EKS Networking
      run: |
        aws cloudformation delete-stack --stack-name my-eks-vpc
