name: Deploy Chess Web App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Fetch kubeconfig
        run: |
          mkdir -p ~/.kube
          bash get-kubeconfig.sh
          cp ~/.kube/config $HOME/.kube/config

      - name: Configure kubectl
        run: |
          kubectl version
          kubectl get pods

      - name: Deploy Chess Web App
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
