name: Provision EKS

on:
  workflow_dispatch:

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Provision EKS Cluster
      run: |
        aws cloudformation create-stack \
          --region ap-south-1 \
          --stack-name chessekscluster \
          --capabilities CAPABILITY_IAM
          --template-file eks-cluster.yaml \
