name: Deploy Chess Game

on:
  push:
    branches:
      - main

jobs:
  provision-or-update-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Check if stack exists
        id: check-stack
        run: |
          aws cloudformation describe-stacks --stack-name MyChessResources >/dev/null 2>&1 || echo "::set-output name=stack-exists::false"
          echo "::set-output name=stack-exists::true"

      - name: Provision or update AWS resources
        if: steps.check-stack.outputs.stack-exists == 'false'
        run: aws cloudformation create-stack --stack-name MyChessResources --template-body file://trial-deployment.yaml

  destroy-resources:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Destroy AWS resources
        run: aws cloudformation delete-stack --stack-name MyChessResources
