name: Deploy Chess Game

on:
  push:
    branches:
      - main

jobs:
  provision-or-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if stack exists
        id: check-stack
        run: |
          # Your script to check if the stack exists goes here
          echo "::set-output name=stack-exists::false"  # For testing purposes

      - name: Provision AWS resources if stack does not exist
        if: steps.check-stack.outputs.stack-exists == 'false'
        run: |
          aws cloudformation create-stack --stack-name MyChessResources --template-body file://trial-deployment.yaml
          echo "::set-output name=stack-action::created"

      - name: Update AWS resources if stack exists
        if: steps.check-stack.outputs.stack-exists == 'true'
        run: |
          aws cloudformation update-stack --stack-name MyChessResources --template-body file://trial-deployment.yaml
          echo "::set-output name=stack-action::updated"

  deploy-container:
    runs-on: ubuntu-latest
    needs: provision-or-update
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Docker
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/chess-game:latest

      - name: Deploy to EKS cluster
        run: kubectl apply -f deployment.yaml && kubectl apply -f cluter.yaml && kubectl apply -f service.yaml

  destroy-resources:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: deploy-container
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Destroy AWS resources
        run: aws cloudformation delete-stack --stack-name MyChessResources
