name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  provision-cluster:
    name: Provision EKS Cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Create EKS Cluster
        run: |
          aws eks create-cluster --name ChessEKSCluster --kubeconfig kubeconfig --region us-east-2 --fargate

      - name: Store kubeconfig
        uses: actions/upload-artifact@v2
        with:
          name: kubeconfig
          path: kubeconfig

  deploy-container:
    name: Deploy Container to EKS
    runs-on: ubuntu-latest
    needs: provision-cluster
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download kubeconfig
        uses: actions/download-artifact@v2
        with:
          name: kubeconfig

      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          mv kubeconfig ~/.kube/config

      - name: Deploy to EKS
        run: |
          kubectl apply -f deployment.yaml -f service.yaml -f cluster.yaml
