name: Workflow

on:
  workflow_dispatch:

jobs:
  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Build and push Docker image to ECR
      run: |
        docker build -t chesswebapp .
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 241367251936.dkr.ecr.ap-south-1.amazonaws.com
        docker tag chesswebapp:latest 241367251936.dkr.ecr.ap-south-1.amazonaws.com/chesswebapp:latest
        docker push 241367251936.dkr.ecr.ap-south-1.amazonaws.com/chesswebapp:latest

  Provision-Networking:
    runs-on: ubuntu-latest
    needs: [Build-and-Push-Docker-Image]  # Wait for build-and-push-image job to complete

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Provision EKS Cluster
      run: |
        aws cloudformation deploy \
          --template-file eks-vpc-stack.yaml \
          --stack-name my-eks-vpc \
          --capabilities CAPABILITY_NAMED_IAM
